//
// EnsWallet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnsWallet200Response: Codable, JSONEncodable, Hashable {

    public var ethAddress: String?

    public init(ethAddress: String? = nil) {
        self.ethAddress = ethAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ethAddress = "eth_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ethAddress, forKey: .ethAddress)
    }
}

