//
// Project.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Project: Codable, JSONEncodable, Hashable {

    public var id: String?
    /** The integer ID of the PBAB project in the contract. */
    public var projectId: Int?
    /** The amount (Wei) required to mint the project. */
    public var purchaseAmount: Int?
    /** The human-readable title of the project (only used in admin panel). */
    public var title: String

    public init(id: String? = nil, projectId: Int? = nil, purchaseAmount: Int? = nil, title: String) {
        self.id = id
        self.projectId = projectId
        self.purchaseAmount = purchaseAmount
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case projectId = "project_id"
        case purchaseAmount = "purchase_amount"
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(purchaseAmount, forKey: .purchaseAmount)
        try container.encode(title, forKey: .title)
    }
}

