//
// Wallet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Wallet: Codable, JSONEncodable, Hashable {

    /** The primary key ID of the **Wallet** */
    public var id: String?
    /** The hashed checksum public address used to identify this wallet. */
    public var ethAddress: String?
    /** The PKCS8-encoded ECC256 public key of the wallet. */
    public var publicKey: String?

    public init(id: String? = nil, ethAddress: String? = nil, publicKey: String? = nil) {
        self.id = id
        self.ethAddress = ethAddress
        self.publicKey = publicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case ethAddress = "eth_address"
        case publicKey = "public_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(ethAddress, forKey: .ethAddress)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
    }
}

