name: Swift Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
